name: ci
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"
permissions:
  contents: read
jobs:
  makefile-descriptions:
    name: "makefile-descriptions"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Check Makefile
        run: make makefile-descriptions
  typos:
    name: "typos"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Check spelling
        uses: crate-ci/typos@master
  bash:
    name: "bash"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install bash dependencies ${{ matrix.os }}
        run: sudo apt-get install shfmt shellcheck coreutils -y
      - name: Check format bash code ${{ matrix.os }}
        run: make bash-check
      - name: Check lint bash code ${{ matrix.os }}
        run: make bash-lint
  dprint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: dprint-check-action
        uses: dprint/check@v2.3
  links-check:
    name: links-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Run lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --base 'https://github.com/rodmoioliveira/soccer-knockout-standings' --verbose --no-progress --exclude-path CHANGELOG.md --exclude '(linkedin|substack)' './**/*.md'
          fail: false
      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
